### ISSUE TITLE
Missing Go modules support

### ISSUE THREAD

**Issue by pbalogh-sa** [goph/licensei#4]
Gopkg.lock is required for licensei:
`Error: could not open dep lock file: open Gopkg.lock: no such file or directory.`
It would be nice to support go modules as well.

**Comment by bonifaido** [comment]
When is this feature coming, we are really interested to use this in production. :)

**Comment by waynz0r** [comment]
👍 💯

**Comment by sagikazarmark** [comment]
Fixed in [0.1.0](https://github.com/goph/licensei/releases/tag/v0.1.0)

**Comment by pbalogh-sa** [comment]
thx @sagikazarmark
